[package]
name = "knight_race"
version = "0.1.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate"
spawn_race = "sozo execute dojo_starter-actions spawn_race --wait"
place_wager = "sozo execute dojo_starter-actions place_wager 1 2 100 --wait"

[dependencies]
dojo = "1.8.0"
starknet = "2.15.2"

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros"]

[dev-dependencies]
cairo_test = "2.15.2"
dojo_cairo_test = "1.8.0"

[profile.sepolia]
rpc_url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"